version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: inheritx_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inheritx_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inheritx-network

networks:
  inheritx-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
